name: Keep Supabase Alive

on:
  schedule:
    # Run at 9 AM UTC on Mondays and Thursdays
    - cron: "0 9 * * 1,4"
  workflow_dispatch: # Allow manual run from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Supabase client
        run: npm install @supabase/supabase-js

      - name: Run ping script
        run: node ping.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
